[package]
name = "retaia-agent"
version = "0.1.0"
edition = "2024"

[lib]
name = "retaia_agent"
path = "src/lib.rs"

[dependencies]
serde_json = "1.0"

[dev-dependencies]
cargo-husky = { version = "1.5.0", default-features = false, features = ["user-hooks"] }
