[package]
name = "retaia-agent"
version = "0.1.0"
edition = "2024"

[lib]
name = "retaia_agent"
path = "src/lib.rs"

[dependencies]
directories = "5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

[dev-dependencies]
cargo-husky = { version = "1.5.0", default-features = false, features = ["user-hooks"] }
tempfile = "3.10"
